### ISSUE TITLE
代码问题求助

### ISSUE THREAD

**Issue by LIShuo-debug** [xhwhht/2022HuaweiSoftwareEliteChallenge#1]
作者您好，我是转码初学者。在阅读您的2022华软挑战赛代码时遇到一些问题。
”按照1：21时刻去分别选择共用多（共用少）的边缘节点去满足客户节点的带宽需求。“
您能否解答一下这个思路的用意呢？我的QQ：596348603，邮箱：596348603@qq.com。希望能得到您的解答，感谢！

**Comment by xhwhht** [comment]
我已看到您的消息，因为最近比较忙碌，如果您不着急我过段时间通过邮箱回复您。

**Comment by LIShuo-debug** [comment]
非常感谢，期待您的解答！

**Comment by xhwhht** [comment]
已回复
